on:
  workflow_dispatch:

steps:
  - uses: actions/checkout@v3
  - uses: actions/download-artifact@v3
  - name: Display structure of downloaded files
    run: ls -R

  - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Latest Release
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .*.bin
        asset_name: DeGourou
        asset_content_type: application/gzip
        
  # - name: upload darwin artifact
  #   uses: actions/upload-release-asset@v1
  #   env:
  #     GITHUB_TOKEN: ${{ github.token }}
  #   with:
  #     upload_url: ${{ steps.create_release.outputs.upload_url }}
  #     asset_path: ./bin/azblogfilter.darwin-amd64.tar.gz
  #     asset_name: azblogfilter.darwin-amd64.tar.gz
  #     asset_content_type: application/gzip

  - name: upload windows artifact
    uses: actions/upload-release-asset@v1
    env:
      GITHUB_TOKEN: ${{ github.token }}
    with:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      asset_path: .*.exe
      asset_name: DeGourou.exe
      asset_content_type: application/zip